server:
  port: ${random.int(8189,9090)}
  error:
    include-message: always
    include-binding-errors: never
    include-stacktrace: never
    include-exception: false

spring:
  application:
    name: swift-wheels-hub-reactive-expense
  webflux:
    base-path: /expense
  data:
    mongodb:
      database: swift_wheels_hub_expense
      username: ${MONGODB_USERNAME}
      password: ${MONGODB_PASSWORD}
      uri: mongodb+srv://${MONGODB_USERNAME}:${MONGODB_PASSWORD}@swiftwheelshubexpense.qfupkzh.mongodb.net
  codec:
    max-in-memory-size: 20MB
  cloud:
    loadbalancer:
      enabled: true
      cache:
        enabled: true
    consul:
      enabled: true
      host: localhost
      port: 8500
      discovery:
        enabled: true
        prefer-ip-address: true
        instanceId: ${spring.application.name}-id
        serviceName: ${spring.application.name}
        healthCheckPath: /actuator/health
        healthCheckInterval: 10s
        hostname: localhost
        failFast: false
    function:
      definition: deletedBookingConsumer;failedInvoiceDlqConsumer;savedBookingConsumer;updatedBookingConsumer
    stream:
      defaultBinder: kafka
      bindings:
        auditLogInfoProducer-out-0:
          destination: ${EXPENSE_AUDIT_LOG_INFO_REACTIVE_TOPIC}
          contentType: application/json
        bookingUpdateProducer-out-0:
          destination: ${BOOKING_UPDATE_REACTIVE_TOPIC}
          contentType: application/json
        carUpdateDetailsProducer-out-0:
          destination: ${INVOICE_CAR_UPDATE_DETAILS_REACTIVE_TOPIC}
          contentType: application/json
        emailNotificationProducer-out-0:
          destination: ${EMAIL_NOTIFICATION_REACTIVE_TOPIC}
          contentType: application/json
        failedInvoiceDlqProducer-out-0:
          destination: ${FAILED_INVOICE_DLQ_REACTIVE_TOPIC}
          contentType: application/json
        deletedBookingConsumer-in-0:
          binder: kafka
          destination: ${DELETED_BOOKING_REACTIVE_TOPIC}
          contentType: application/json
          group: ${EXPENSE_CONSUMER_GROUP}
        failedInvoiceDlqConsumer-in-0:
          binder: kafka
          destination: ${FAILED_INVOICE_DLQ_REACTIVE_TOPIC}
          contentType: application/json
          group: ${EXPENSE_CONSUMER_GROUP}
        savedBookingConsumer-in-0:
          binder: kafka
          destination: ${SAVED_BOOKING_REACTIVE_TOPIC}
          contentType: application/json
          group: ${EXPENSE_CONSUMER_GROUP}
        updatedBookingConsumer-in-0:
          binder: kafka
          destination: ${UPDATED_BOOKING_REACTIVE_TOPIC}
          contentType: application/json
          group: ${EXPENSE_CONSUMER_GROUP}
      kafka:
        binder:
          auto-create-topics: true
          auto-add-partitions: false
          consumer-properties:
            key.deserializer: org.apache.kafka.common.serialization.StringDeserializer
            value.deserializer: org.apache.kafka.common.serialization.StringDeserializer
            allow.auto.create.topics: true
            auto.offset.reset: latest
        bindings:
          deletedBookingConsumer-in-0:
            consumer:
              ack-mode: MANUAL_IMMEDIATE
              standard-headers: both
          failedInvoiceDlqConsumer-in-0:
            consumer:
              ack-mode: MANUAL_IMMEDIATE
              standard-headers: both
          savedBookingConsumer-in-0:
            consumer:
              ack-mode: MANUAL_IMMEDIATE
              standard-headers: both
          updatedBookingConsumer-in-0:
            consumer:
              ack-mode: MANUAL_IMMEDIATE
              standard-headers: both
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      enable-auto-commit: false
    producer:
      acks: all
  sendgrid:
    api-key: ${SENDGRID_API_KEY}
  web:
    resources:
      add-mappings: false

springdoc:
  swagger-ui:
    enabled: true
    path: /definition/swagger-ui.html
    operationsSorter: method
  api-docs:
    path: /definition/v3/api-docs

management:
  server:
    port: ${server.port}
  endpoint:
    health:
      group:
        custom:
          show-components: always
          show-details: always
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,loggers,prometheus
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true

logging:
  level:
    org:
      springframework:
        security: ERROR
        web: ERROR
        data:
          mongodb:
            core:
              ReactiveMongoTemplate: ERROR

apikey:
  secret: ${API_KEY_SECRET}

cors:
  mapping: '/**'
  allowedOrigins: '*'
  allowedMethods: '*'
  allowedHeaders: '*'
  codecMaxInMemorySizeInMb: 20

mongo-operations:
  enabled: true

scheduled:
  fixedDelay: 3000

audit:
  enabled: true
