server:
  port: ${random.int(8189,9090)}
  error:
    include-message: always
    include-binding-errors: never
    include-stacktrace: never
    include-exception: false

spring:
  application:
    name: auto-hub-reactive-request-validator
  codec:
    max-in-memory-size: 20MB
  cloud:
    loadbalancer:
      enabled: true
      cache:
        enabled: true
    consul:
      enabled: true
      host: localhost
      port: 8500
      discovery:
        enabled: true
        prefer-ip-address: true
        instanceId: ${spring.application.name}-id
        serviceName: ${spring.application.name}
        healthCheckPath: /actuator/health
        healthCheckInterval: 10s
        hostname: localhost
        failFast: false
  redis:
    host: ${REDIS_HOST}
    password: ${REDIS_PASSWORD}
    port: 6379
  data:
    redis:
      database: 0
  web:
    resources:
      add-mappings: false

logging:
  level:
    org:
      springframework:
        security: ERROR
        web: ERROR

cors:
  mapping: '/**'
  allowedOrigins: '*'
  allowedMethods: '*'
  allowedHeaders: '*'
  codecMaxInMemorySizeInMb: 20

swagger:
  endpoints:
    - identifier: agency
      url: http://auto-hub-reactive-agency/agency/definition/v3/api-docs
    - identifier: ai
      url: http://auto-hub-reactive-ai/ai/definition/v3/api-docs
    - identifier: bookings
      url: http://auto-hub-reactive-booking/bookings/definition/v3/api-docs
    - identifier: customers
      url: http://auto-hub-reactive-customer/customers/definition/v3/api-docs
    - identifier: expense
      url: http://auto-hub-reactive-expense/expense/definition/v3/api-docs

management:
  server:
    port: ${server.port}
  endpoint:
    health:
      group:
        custom:
          show-components: always
          show-details: always
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,loggers,prometheus
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
