server:
  port: ${random.int(8189,9090)}
  error:
    include-message: always
    include-binding-errors: never
    include-stacktrace: never
    include-exception: false

spring:
  application:
    name: swift-wheels-hub-reactive-api-gateway
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/swift-wheels-hub
          jwk-set-uri: http://localhost:8080/realms/swift-wheels-hub/protocol/openid-connect/certs
  codec:
    max-in-memory-size: 20MB
  cloud:
    loadbalancer:
      enabled: true
    ribbon:
      enabled: false
    consul:
      config:
        enabled: false
      host: localhost
      port: 8500
      discovery:
        instanceId: ${spring.application.name}-id
        serviceName: ${spring.application.name}
        healthCheckPath: /actuator/health
        healthCheckInterval: 5s
        hostname: localhost
        failFast: false
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: agency
          uri: lb://swift-wheels-hub-reactive-agency
          predicates:
            - Path=/agency/**
          filters:
            - name: LanguageHeader
              args:
                language: "EN"
        - id: booking
          uri: lb://swift-wheels-hub-reactive-booking
          predicates:
            - Path=/bookings/**
          filters:
            - name: LanguageHeader
              args:
                language: "EN"
        - id: customer
          uri: lb://swift-wheels-hub-reactive-customer
          predicates:
            - Path=/customers/**
          filters:
            - name: LanguageHeader
              args:
                language: "EN"
        - id: expense
          uri: lb://swift-wheels-hub-reactive-expense
          predicates:
            - Path=/expense/**
          filters:
            - name: LanguageHeader
              args:
                language: "EN"

management:
  server:
    port: ${server.port}
  endpoint:
    loggers:
      enabled: true
    health:
      group:
        custom:
          show-components: always
          show-details: always
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,loggers,prometheus
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true

logging:
  level:
    org:
      springframework:
        security: DEBUG

apikey-secret: ${API_KEY_SECRET}

request-validator-url: http://swift-wheels-hub-reactive-request-validator/validate
