server:
  port: ${PORT:8183}
  error:
    include-message: always
    include-binding-errors: never
    include-stacktrace: never
    include-exception: false

spring:
  application:
    name: car-rental-booking
  webflux:
    base-path: /bookings
  data:
    mongodb:
      database: car_rental_booking
      username: ${MONGODB_USERNAME}
      password: ${MONGODB_PASSWORD}
      uri: mongodb+srv://${MONGODB_USERNAME}:${MONGODB_PASSWORD}@cluster0.2wuy2po.mongodb.net/
  cloud:
    discovery:
      enabled: true
    function:
      definition: deletedUserConsumer
    stream:
      bindings:
        savedBookingProducer-out-0:
          destination: ${SAVED_BOOKING_PRODUCER_REACTIVE_TOPIC}
          contentType: application/json
        updatedBookingProducer-out-0:
          destination: ${UPDATED_BOOKING_PRODUCER_REACTIVE_TOPIC}
          contentType: application/json
        deletedBookingProducer-out-0:
          destination: ${DELETED_BOOKING_PRODUCER_REACTIVE_TOPIC}
          contentType: application/json
        auditLogInfoProducer-out-0:
          destination: ${BOOKING_AUDIT_LOG_INFO_PRODUCER_REACTIVE_TOPIC}
          contentType: application/json
        deletedUserConsumer-in-0:
          binder: kafka
          destination: ${DELETED_USER_PRODUCER_REACTIVE_TOPIC}
          contentType: application/json
          group: ${BOOKING_CONSUMER_GROUP}
      kafka:
        binder:
          auto-create-topics: false
          auto-add-partitions: false
          consumer-properties:
            key.deserializer: org.apache.kafka.common.serialization.StringDeserializer
            value.deserializer: org.apache.kafka.common.serialization.StringDeserializer
            allow.auto.create.topics: false
  kafka:
    bootstrap-servers: localhost:9092
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${EUREKA_USER}:${EUREKA_PASSWORD}@localhost:8861/eureka
    registryFetchIntervalSeconds: 5
  instance:
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 10

springdoc:
  swagger-ui:
    enabled: true
    path: /definition/swagger-ui.html
    operationsSorter: method
  api-docs:
    path: /definition/v3/api-docs
  show-actuator: true

ribbon:
  eureka:
    enabled: false

logging:
  level:
    org:
      springframework:
        security: DEBUG
        web:
          csrf:
            CsrfFilter: DEBUG

authentication:
  type: apikey
  secret: ${API_KEY_SECRET}

cross-origin: '*'

webclient:
  url:
    car-rental-agency-branches: lb://car-rental-agency/agency/branches
    car-rental-agency-cars: lb://car-rental-agency/agency/cars
    car-rental-agency-rental-offices: lb://car-rental-agency/agency/rental-offices
    car-rental-agency-employees: lb://car-rental-agency/agency/employees

scheduled:
  fixedDelay: 5000

audit:
  enabled: true
